### Revisar que la API funciona
GET http://localhost:3000/health


### Registrar usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "Alejandro Ortega",
  "correo": "alexios@iteso.mx",
  "password": "Alex1234",
  "rol": "alumno"
}


### Iniciar sesión
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "correo": "alexios@iteso.mx",
  "password": "Alex1234"
}

### Ver mis tareas como alumno
GET http://localhost:3000/api/tareas/mias
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDBjYzVjZThiZmQ2YWUxYjE4MTk1NiIsImNvcnJlbyI6ImFsZXhpb3NAaXRlc28ubXgiLCJyb2wiOiJhbHVtbm8iLCJpYXQiOjE3Nzg0Mzc0MDksImV4cCI6MTc3ODQ2NjIwOX0.XLn-_XAAbcthrgOwDYKvb38DteNTJ0eFTnR_rGoJntI
